version: '2'
services:
  wmsdemo-postgresql:
    image: postgres:12.3
    volumes:
      - wms-postgresdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wmsdemo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
